ext-swoole:
  type: php-extension
  artifact:
    source:
      type: ghtar
      repo: swoole/swoole-src
      extract: php-src/ext/swoole
      prefer-stable: true
    metadata:
      license-files: [LICENSE]
      license: Apache-2.0
  depends:
    - libcares
    - brotli
    - nghttp2
    - zlib
    - ext-openssl
    - ext-curl
  suggests:
    - ext-sockets
  lang: cpp
  php-extension:
    os:
      - Linux
      - Darwin
    arg-type: custom
