<?php

declare(strict_types=1);

return [
    'Aegis' => [
        'package' => 'phalanx-php/aegis',
        'description' => 'Managed async for PHP 8.4+ on Swoole',
        'type' => 'library',
        'namespace' => 'Phalanx\\',
        'smokeClass' => 'Phalanx\\Runtime\\RuntimePolicy',
        'testNamespace' => 'Phalanx\\Aegis\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'ext-swoole' => '^6.0',
            'phalanx-php/themis' => '^0.6',
            'symfony/process' => '^7.0 || ^8.0',
            'symfony/uid' => '^7.0 || ^8.0',
        ],
        'devRequires' => [
            'phalanx-php/archon' => '^0.6',
            'phalanx-php/stoa' => '^0.6',
            'phalanx-php/hydra' => '^0.6',
            'swoole/ide-helper' => '^6.0',
            'phpstan/phpstan' => '^2.0',
            'phpunit/phpunit' => '^13.0',
            'rector/rector' => '^2.0',
            'slevomat/coding-standard' => '^8.15',
            'squizlabs/php_codesniffer' => '^3.10 || ^4.0',
        ],
        'bins' => [
            'bin/regenerate-accessors',
            'bin/check-accessors-in-sync',
        ],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'async',
            'concurrency',
            'coroutines',
            'swoole',
            'supervisor',
            'parallel',
            'structured-concurrency',
        ],
        'suggests' => [
            'phalanx-php/styx' => 'Reactive stream primitives (Emitter, ScopedStream, Channel)',
            'phalanx-php/archon' => 'CLI application framework',
            'phalanx-php/stoa' => 'HTTP server framework',
            'phalanx-php/hydra' => 'Worker process parallelism',
            'spatie/backtrace' => 'Enhanced stack traces',
            'symfony/runtime' => 'For symfony/runtime integration',
            'symfony/dotenv' => 'For .env file support',
        ],
        'allowPlugins' => [
            'dealerdirect/phpcodesniffer-composer-installer' => true,
        ],
        'sortPackages' => true,
        'devClassmap' => [
            'tests/Support/Fixtures/',
        ],
    ],
    'Archon' => [
        'package' => 'phalanx-php/archon',
        'description' => 'CLI application framework for Phalanx',
        'type' => 'library',
        'namespace' => 'Phalanx\\Archon\\',
        'smokeClass' => 'Phalanx\\Archon\\Application\\Archon',
        'testNamespace' => 'Phalanx\\Archon\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'phalanx-php/aegis' => '^0.6',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'cli',
            'console',
            'async',
            'phalanx',
        ],
        'suggests' => [
            'symfony/runtime' => 'For Symfony Runtime integration via Archon::starting()',
            'phalanx-php/styx' => 'For streaming data through console commands',
            'phalanx-php/hydra' => 'For worker process parallelism in CLI tasks',
        ],
        'bundles' => [
            'Phalanx\\Archon\\Testing\\ArchonTestableBundle',
        ],
    ],
    'Argos' => [
        'package' => 'phalanx-php/argos',
        'description' => 'Network discovery, probing, and device management for Phalanx',
        'type' => 'library',
        'namespace' => 'Phalanx\\Argos\\',
        'smokeClass' => 'Phalanx\\Argos\\NetworkConfig',
        'testNamespace' => 'Phalanx\\Argos\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'ext-swoole' => '*',
            'phalanx-php/aegis' => '^0.6',
            'mlocati/ip-lib' => '^1.22',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'network',
            'discovery',
            'mdns',
            'ssdp',
            'wol',
            'ping',
            'scan',
            'async',
            'swoole',
        ],
        'suggests' => [],
    ],
    'Athena' => [
        'package' => 'phalanx-php/athena',
        'description' => 'Agent activity runtime for Phalanx - supervised turns, effects, grants, hooks, and Panoply invocation loops',
        'type' => 'library',
        'namespace' => 'Phalanx\\Athena\\',
        'smokeClass' => 'Phalanx\\Athena\\Athena',
        'testNamespace' => 'Phalanx\\Athena\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'phalanx-php/aegis' => '^0.6',
            'phalanx-php/iris' => '^0.6',
            'phalanx-php/panoply' => '^0.6',
            'phalanx-php/styx' => '^0.6',
            'phalanx-php/surreal' => '^0.6',
            'symfony/uid' => '^7.0 || ^8.0',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'ai',
            'agent',
            'llm',
            'activity',
            'effects',
            'grants',
            'panoply',
            'streaming',
            'tools',
            'async',
        ],
        'suggests' => [
            'phalanx-php/archon' => 'CLI agent commands via Archon command lifecycle',
            'phalanx-php/hermes' => 'Real-time agent sessions over WebSocket',
            'phalanx-php/theatron' => 'TUI rendering of agent work via CompositeStream',
        ],
    ],
    'Cli' => [
        'package' => 'phalanx-php/cli',
        'description' => 'Phalanx CLI: doctor, Swoole installer using PIE, and project scaffolding',
        'type' => 'library',
        'namespace' => 'Phalanx\\Cli\\',
        'smokeClass' => 'Phalanx\\Cli\\PhalanxApplication',
        'testNamespace' => 'Phalanx\\Cli\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'symfony/console' => '^7.4 || ^8.0',
            'symfony/process' => '^7.4 || ^8.0',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [
            'bin/phalanx',
        ],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'cli',
            'phalanx',
            'swoole',
            'installer',
            'doctor',
        ],
        'suggests' => [],
    ],
    'Enigma' => [
        'package' => 'phalanx-php/enigma',
        'description' => 'Non-blocking SSH command execution, file transfer, and tunnel management as Phalanx tasks',
        'type' => 'library',
        'namespace' => 'Phalanx\\Enigma\\',
        'smokeClass' => 'Phalanx\\Enigma\\SshConfig',
        'testNamespace' => 'Phalanx\\Enigma\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'phalanx-php/aegis' => '^0.6',
            'phalanx-php/grammata' => '^0.6',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [],
        'suggests' => [],
    ],
    'Grammata' => [
        'package' => 'phalanx-php/grammata',
        'description' => 'Async-aware filesystem operations for Phalanx',
        'type' => 'library',
        'namespace' => 'Phalanx\\Grammata\\',
        'smokeClass' => 'Phalanx\\Grammata\\Grammata',
        'testNamespace' => 'Phalanx\\Grammata\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'phalanx-php/aegis' => '^0.6',
            'phalanx-php/styx' => '^0.6',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'filesystem',
            'async',
            'file',
            'stream',
            'swoole',
        ],
        'suggests' => [
            'phalanx-php/hydra' => 'Use for application-owned slow-storage offload when filesystem work should run in workers',
        ],
    ],
    'Hermes' => [
        'package' => 'phalanx-php/hermes',
        'description' => 'Native WebSocket server and client for Phalanx',
        'type' => 'library',
        'namespace' => 'Phalanx\\Hermes\\',
        'smokeClass' => 'Phalanx\\Hermes\\Hermes',
        'testNamespace' => 'Phalanx\\Hermes\\Tests\\',
        'testNamespaces' => [
            'Phalanx\\Hermes\\Tests\\' => 'tests/',
            'Phalanx\\Hermes\\Client\\Tests\\' => 'tests/Client/',
        ],
        'requires' => [
            'php' => '^8.4',
            'ext-swoole' => '^6.0',
            'phalanx-php/aegis' => '^0.6',
            'phalanx-php/stoa' => '^0.6',
            'phalanx-php/styx' => '^0.6',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'websocket',
            'ws',
            'client',
            'server',
            'swoole',
        ],
        'suggests' => [],
    ],
    'Hydra' => [
        'package' => 'phalanx-php/hydra',
        'description' => 'Worker process parallelism for Phalanx',
        'type' => 'library',
        'namespace' => 'Phalanx\\Hydra\\',
        'smokeClass' => 'Phalanx\\Hydra\\Hydra',
        'testNamespace' => 'Phalanx\\Hydra\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'phalanx-php/aegis' => '^0.6',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [
            'bin/phalanx-worker',
        ],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'parallel',
            'worker',
            'process',
            'ipc',
            'swoole',
        ],
        'suggests' => [],
    ],
    'Iris' => [
        'package' => 'phalanx-php/iris',
        'description' => 'Outbound HTTP client for Phalanx',
        'type' => 'library',
        'namespace' => 'Phalanx\\Iris\\',
        'smokeClass' => 'Phalanx\\Iris\\Iris',
        'testNamespace' => 'Phalanx\\Iris\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'ext-swoole' => '^6.0',
            'phalanx-php/aegis' => '^0.6',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'http',
            'client',
            'outbound',
            'swoole',
        ],
        'suggests' => [],
    ],
    'PHPStan' => [
        'package' => 'phalanx-php/phpstan',
        'description' => 'PHPStan safety rules for Phalanx concurrent and parallel PHP',
        'type' => 'phpstan-extension',
        'namespace' => 'Phalanx\\PHPStan\\',
        'smokeClass' => 'Phalanx\\PHPStan\\Support\\PathPolicy',
        'testNamespace' => 'Phalanx\\PHPStan\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'phpstan/phpstan' => '^2.0',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'phpstan',
            'phalanx',
            'swoole',
            'static-analysis',
            'async',
        ],
        'suggests' => [],
        'phpstanIncludes' => [
            'extension.neon',
        ],
        'sortPackages' => true,
    ],
    'Panoply' => [
        'package' => 'phalanx-php/panoply',
        'description' => 'Agent abstraction for PHP 8.4+: contracts, provider/transport adapters, conversation parsers, vendor HomeDirs',
        'type' => 'library',
        'namespace' => 'Phalanx\\Panoply\\',
        'smokeClass' => 'Phalanx\\Panoply\\Agent',
        'testNamespace' => 'Phalanx\\Panoply\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'symfony/uid' => '^7.0 || ^8.0',
            'symfony/yaml' => '^7.0 || ^8.0',
        ],
        'devRequires' => [
            'swoole/ide-helper' => '^6.0',
            'phalanx-php/aegis' => '^0.6',
            'phalanx-php/iris' => '^0.6',
            'phpstan/phpstan' => '^2.0',
            'phpunit/phpunit' => '^13.0',
            'rector/rector' => '^2.0',
            'slevomat/coding-standard' => '^8.15',
            'squizlabs/php_codesniffer' => '^3.10 || ^4.0',
            'php-collective/toml' => '^0.1.3',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'agents',
            'llm',
            'anthropic',
            'openai',
            'gemini',
            'ollama',
            'agent-abstraction',
            'conversation-parser',
            'swoole',
        ],
        'suggests' => [
            'phalanx-php/aegis' => 'Required for the Aegis Runtime adapter; enables scope-bound cancellation and cleanup',
            'phalanx-php/athena' => 'Required for the Athena Provider adapter; bridges Athena\'s AgentEvent stream to panoply Cues',
            'phalanx-php/iris' => 'Required for the Iris Transport adapter; Swoole-native streaming HTTP',
            'phalanx-php/grammata' => 'Required for HomeDir parsers; managed file I/O with FilePool',
            'phalanx-php/archon' => 'Required for the panoply:agents:scan Archon command',
            'ext-sqlite3' => 'Required for Codex HomeDir sqlite-backed history',
            'ext-swoole' => 'Required for the Iris transport and Aegis runtime',
            'php-collective/toml' => 'Required for reading Codex config.toml settings; without it Settings operates in no-op mode and asString/asInt/etc. throw',
        ],
        'allowPlugins' => [
            'dealerdirect/phpcodesniffer-composer-installer' => true,
        ],
        'sortPackages' => true,
    ],
    'Skopos' => [
        'package' => 'phalanx-php/skopos',
        'description' => 'Dev server orchestrator with process management, output multiplexing, and file watching',
        'type' => 'library',
        'namespace' => 'Phalanx\\Skopos\\',
        'smokeClass' => 'Phalanx\\Skopos\\Skopos',
        'testNamespace' => 'Phalanx\\Skopos\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'ext-swoole' => '^6.0',
            'phalanx-php/aegis' => '^0.6',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [
            'bin/skopos',
        ],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [],
        'suggests' => [],
    ],
    'Stoa' => [
        'package' => 'phalanx-php/stoa',
        'description' => 'HTTP server framework for Phalanx',
        'type' => 'library',
        'namespace' => 'Phalanx\\Stoa\\',
        'smokeClass' => 'Phalanx\\Stoa\\Stoa',
        'testNamespace' => 'Phalanx\\Stoa\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'guzzlehttp/psr7' => '^2.0',
            'nikic/fast-route' => '^2.0',
            'ext-swoole' => '^6.0',
            'phalanx-php/aegis' => '^0.6',
        ],
        'devRequires' => [
            'phalanx-php/iris' => '^0.6',
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'http',
            'server',
            'routing',
            'async',
            'fastroute',
            'swoole',
        ],
        'suggests' => [
            'symfony/runtime' => 'For Symfony Runtime integration via Stoa::starting()',
            'phalanx-php/hydra' => 'For worker process parallelism in request handlers',
        ],
        'bundles' => [
            'Phalanx\\Stoa\\Testing\\StoaTestableBundle',
        ],
    ],
    'Styx' => [
        'package' => 'phalanx-php/styx',
        'description' => 'Reactive stream primitives for Phalanx',
        'type' => 'library',
        'namespace' => 'Phalanx\\Styx\\',
        'smokeClass' => 'Phalanx\\Styx\\Styx',
        'testNamespace' => 'Phalanx\\Styx\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'ext-swoole' => '^6.0',
            'phalanx-php/aegis' => '^0.6',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'reactive',
            'stream',
            'channel',
            'emitter',
            'backpressure',
            'async',
            'swoole',
        ],
        'suggests' => [],
    ],
    'Surreal' => [
        'package' => 'phalanx-php/surreal',
        'description' => 'SurrealDB RPC and live-query client for Phalanx using Iris, Hermes, and Aegis runtime supervision',
        'type' => 'library',
        'namespace' => 'Phalanx\\Surreal\\',
        'smokeClass' => 'Phalanx\\Surreal\\Surreal',
        'testNamespace' => 'Phalanx\\Surreal\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'phalanx-php/aegis' => '^0.6',
            'phalanx-php/hermes' => '^0.6',
            'phalanx-php/iris' => '^0.6',
            'phalanx-php/themis' => '^0.6',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'surrealdb',
            'phalanx',
            'aegis',
            'iris',
            'http',
            'rpc',
        ],
        'suggests' => [],
    ],
    'Themis' => [
        'package' => 'phalanx-php/themis',
        'description' => 'Config hydration and environment validation primitives for Phalanx',
        'type' => 'library',
        'namespace' => 'Phalanx\\Themis\\',
        'smokeClass' => 'Phalanx\\Themis\\ConfigFactory',
        'testNamespace' => 'Phalanx\\Themis\\Tests\\',
        'requires' => [
            'php' => '^8.4',
        ],
        'devRequires' => [
            'phpunit/phpunit' => '^13.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'keywords' => [
            'config',
            'env',
            'hydration',
            'validation',
        ],
        'suggests' => [],
    ],
    'Theatron' => [
        'package' => 'phalanx-php/theatron',
        'description' => 'Terminal UI and agent collaboration framework for Phalanx PHP',
        'type' => 'library',
        'namespace' => 'Phalanx\\Theatron\\',
        'smokeClass' => 'Phalanx\\Theatron\\Theatron',
        'testNamespace' => 'Phalanx\\Theatron\\Tests\\',
        'requires' => [
            'php' => '^8.4',
            'ext-swoole' => '^6.0',
            'ext-pcntl' => '*',
            'ext-mbstring' => '*',
            'phalanx-php/aegis' => '^0.6',
            'phalanx-php/athena' => '^0.6',
            'phalanx-php/grammata' => '^0.6',
            'phalanx-php/panoply' => '^0.6',
        ],
        'devRequires' => [
            'slevomat/coding-standard' => '*',
            'squizlabs/php_codesniffer' => '*',
            'rector/rector' => '^2.4',
            'rector/swiss-knife' => '^2.3',
            'phpunit/phpunit' => '^13.1',
            'phpstan/phpstan' => '^2.0',
        ],
        'bins' => [],
        'branchAlias' => '0.6.x-dev',
        'autoloadFiles' => [
            'src/Tui/Kit/functions.php',
        ],
        'keywords' => [
            'agent-collab',
            'terminal-ui',
            'theatron',
        ],
        'suggests' => [],
        'allowPlugins' => [
            'dealerdirect/phpcodesniffer-composer-installer' => true,
        ],
    ],
];
