name: full
description: Full runtime (all extensions, all Swoole features, all Phalanx packages)

php:
  version: "8.4"
  ini:
    memory_limit: "2G"
    max_execution_time: "0"
  ini_path: "${DORY_INI_PATH:-~/.config/dory}"
  ini_scan_dir: "${DORY_INI_SCAN_DIR:-~/.config/dory/conf.d}"

extensions:
  required:
    - swoole
    - openssl
    - curl
    - mbstring
    - pcntl
    - sockets
    - posix
    - filter
    - tokenizer
    - ctype
    - iconv
  optional:
    - pdo_pgsql
    - pdo_sqlite
    - pdo_mysql
    - redis
    - readline

swoole:
  version: "26.2.0"
  features:
    openssl: true
    http2: true
    hook_curl: true
    cares: true
    sockets: true
    postgres: true
    mysqlnd: true

phalanx:
  packages:
    - aegis
    - stoa
    - iris
    - styx
    - dory
    - archon
    - themis
    - enigma
    - grammata
    - hydra
    - athena
    - panoply
    - postgres
    - hermes
    - argos
    - surreal

spc:
  registries:
    - tools/spc-swoole
