name: 'Monorepo Split'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  split_monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - phalanx-aegis
          - phalanx-aegis-codegen
          - phalanx-archon
          - phalanx-argos
          - phalanx-athena
          - phalanx-cli
          - phalanx-eidolon
          - phalanx-enigma
          - phalanx-grammata
          - phalanx-hermes
          - phalanx-hydra
          - phalanx-iris
          - phalanx-phpstan
          - phalanx-skopos
          - phalanx-stoa
          - phalanx-styx
          - phalanx-surreal

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: symplify/monorepo-split-github-action@v2.3.0
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'phalanx-php'
          repository_name: '${{ matrix.package }}'
          tag: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
