name: 'Monorepo Split'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  split_monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: phalanx-aegis
            module: Aegis
          - package: phalanx-archon
            module: Archon
          - package: phalanx-argos
            module: Argos
          - package: phalanx-athena
            module: Athena
          - package: phalanx-cli
            module: Cli
          - package: phalanx-eidolon
            module: Eidolon
          - package: phalanx-enigma
            module: Enigma
          - package: phalanx-grammata
            module: Grammata
          - package: phalanx-hermes
            module: Hermes
          - package: phalanx-hydra
            module: Hydra
          - package: phalanx-iris
            module: Iris
          - package: phalanx-panoply
            module: Panoply
          - package: phalanx-phpstan
            module: PHPStan
          - package: phalanx-skopos
            module: Skopos
          - package: phalanx-stoa
            module: Stoa
          - package: phalanx-styx
            module: Styx
          - package: phalanx-surreal
            module: Surreal
          - package: phalanx-theatron
            module: Theatron

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: symplify/monorepo-split-github-action@v2.3.0
        with:
          package_directory: 'framework/src/${{ matrix.module }}'
          repository_organization: 'phalanx-php'
          repository_name: '${{ matrix.package }}'
          tag: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
